question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
{"text": "The Great Wall of China is visible from space.", "answer": "False"},
{"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
{"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
{"text": "Lightning never strikes the same place twice.", "answer": "False"},
{"text": "Bananas grow on trees.", "answer": "False"},
{"text": "The capital of Australia is Sydney.", "answer": "False"},
{"text": "Octopuses have three hearts.", "answer": "True"},
{"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
{"text": "The human body has four lungs.", "answer": "False"},
{"text": "The currency of Japan is the Yen.", "answer": "True"},
{"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
{"text": "Bats are blind.", "answer": "False"},
{"text": "The Atlantic Ocean is the biggest ocean on Earth.", "answer": "False"},
{"text": "Shakespeare wrote 37 plays.", "answer": "True"},
{"text": "Penguins are only found in the Arctic.", "answer": "False"},
{"text": "The human nose and ears continue to grow throughout life.", "answer": "True"},
{"text": "Honey never spoils.", "answer": "True"},
{"text": "The Mona Lisa was painted by Leonardo da Vinci.", "answer": "True"},
{"text": "A group of crows is called a murder.", "answer": "True"},
{"text": "The speed of light is approximately 300,000 kilometers per second.", "answer": "True"},
{"text": "Humans and dinosaurs coexisted.", "answer": "False"},
{"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
{"text": "The capital of Canada is Toronto.", "answer": "False"},
{"text": "An octopus has eight arms.", "answer": "True"},
{"text": "The chemical symbol for gold is Au.", "answer": "True"},
{"text": "The Sahara is the largest desert in the world.", "answer": "False"},
{"text": "A leap year occurs every four years.", "answer": "True"},
{"text": "The piano has 88 keys.", "answer": "True"}
]
